CREATE TABLE Usuario (
	Cod_Usu VARCHAR(8) CONSTRAINT PK_Cod_Usu PRIMARY KEY,
	Cod_Emp VARCHAR(8) NOT NULL,
	Nivel_Usu VARCHAR(2) NOT NULL,
	Nom_Usu VARCHAR(30) NOT NULL,
	Password VARCHAR(10) NOT NULL,
	Activo VARCHAR(2) NOT NULL
)