CREATE TABLE Empleado (
	Cod_Emp VARCHAR(8) CONSTRAINT PK_Cod_Emp PRIMARY KEY,
	Nom_Emp VARCHAR(40) NOT NULL,
	Dir_Emp VARCHAR(40),
	Cod_Dis VARCHAR(8) NOT NULL,
	Cargo VARCHAR(40) NOT NULL,
	Edad INT,
	Tel NUMERIC(9) NOT NULL,
	Ingreso DATETIME NOT NULL,
	Clave VARCHAR(20) NOT NULL
)