-- TABLA CATEGORIA
CREATE TABLE Categoria (
	Cod_Cate VARCHAR(8) CONSTRAINT PK_Cod_Cate PRIMARY KEY,
	Nom_Cate VARCHAR(40) NOT NULL CONSTRAINT UK_Nom_Cate UNIQUE
);

--TABLA PRESENTACION
CREATE TABLE Presentacion (
	Cod_Pres VARCHAR(8) CONSTRAINT PK_Cod_Pres PRIMARY KEY,
	Nom_Pres VARCHAR(40) NOT NULL
);

--TABLA DETALLEORDENPRO
CREATE TABLE DetalleOrdenPro (
	Num_OrdenP INT IDENTITY(1,1) CONSTRAINT PK_Num_OrdenP PRIMARY KEY,
	Cod_Pro VARCHAR(8) NOT NULL,
	Nom_Pro VARCHAR(40),
	Cantidad INT,
	Precio_Venta DECIMAL(10,2),
	Importe MONEY
);