--FOREIGN PRODUCTO
ALTER TABLE Producto
ADD CONSTRAINT FK_Cod_Cate FOREIGN KEY(Cod_Cate) REFERENCES Categoria(Cod_Cate)

ALTER TABLE Producto
ADD CONSTRAINT FK_Cod_Pres FOREIGN KEY(Cod_Pres) REFERENCES Presentacion(Cod_Pres)

--FOREIGN DetalleOrdenPro
ALTER TABLE DetalleOrdenPro

--ALTER TABLE EN PRESENTACION
ALTER TABLE Categoria
ALTER COLUMN Nom_Cate VARCHAR(50) NOT NULL



