SELECT
	p.N_NOMBRE, h.N_HOTEL, 
	DATENAME(DW,ph.D_INICIO) + ', ' + CONVERT(VARCHAR(20),ph.D_INICIO,113) AS F_INICIO,
	DATENAME(DW,ph.D_FIN)  + ', ' + CONVERT(VARCHAR(20),ph.D_FIN,113) AS F_FIN
	
FROM
	PARTICIPANTE_HOTEL ph INNER JOIN PARTICIPANTE p ON (ph.C_ASOCIADO = p.C_ASOCIADO)
						  INNER JOIN HOTEL h ON (ph.C_HOTEL = h.C_HOTEL)
WHERE
	p.N_NOMBRE = 'DONATELO PEDELO'