--LA TABULA RASA DE USUARIOS
ALTER TABLE Usuario
ADD CONSTRAINT FK_USU_Cod_Emp FOREIGN KEY(Cod_Emp) REFERENCES Empleado(Cod_Emp)

--EMPLEADO
ALTER TABLE Empleado
ADD CONSTRAINT FK_EMP_Cod_Dis FOREIGN KEY(Cod_Dis) REFERENCES Distrito(Cod_Dis)

--CLIENTES
ALTER TABLE Clientes
ADD CONSTRAINT FK_CLI_Cod_Dis FOREIGN KEY(Cod_Dis) REFERENCES Distrito(Cod_Dis)

--FACTURA
ALTER TABLE Factura
ADD CONSTRAINT FK_FAC_Cod_Emp FOREIGN KEY(Cod_Emp) REFERENCES Empleado(Cod_Emp)

ALTER TABLE Factura
ADD CONSTRAINT FK_FAC_Cod_Cli FOREIGN KEY(Cod_Cli) REFERENCES Clientes(Cod_Cli)

ALTER TABLE Factura
ADD CONSTRAINT FK_FAC_Num_OrdenPedido FOREIGN KEY(Num_OrdenPedido) REFERENCES OrdenPedido(Num_OrdenPedido)

--PROVEEDOR
ALTER TABLE Proveedor
ADD CONSTRAINT FK_PRO_ID_Distrito FOREIGN KEY(ID_Distrito) REFERENCES Distrito(Cod_Dis)

--ORDENPEDIDO
ALTER TABLE OrdenPedido
ADD CONSTRAINT FK_OP_Cod_Cli FOREIGN KEY(Cod_Cli) REFERENCES Clientes(Cod_Cli)

ALTER TABLE OrdenPedido
ADD CONSTRAINT FK_OP_Cod_Emp FOREIGN KEY(Cod_Emp) REFERENCES Empleado(Cod_Emp)

ALTER TABLE OrdenPedido
ADD CONSTRAINT FK_OP_Cod_Prod FOREIGN KEY(Cod_Prod) REFERENCES Producto(Cod_Pro)

--PRODUCTO
ALTER TABLE Producto
ADD CONSTRAINT FK_PRO_Cod_Prov FOREIGN KEY(Cod_Prov) REFERENCES Proveedor(Cod_Prov)