CREATE TABLE Clientes (
	Cod_Cli VARCHAR(8) CONSTRAINT PK_Cod_Cli PRIMARY KEY,
	Nom_Cli VARCHAR(40) NOT NULL,
	Dir_Cli VARCHAR(40),
	Cod_Dis VARCHAR(8),
	Sexo VARCHAR(1) NOT NULL,
	DNI VARCHAR(9) NOT NULL,
	Telefono NUMERIC(9) NOT NULL
)	